In [22]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [23]:
#provide data
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1)) #ınput
y = np.array([5, 20, 14, 32, 22, 38]) #output

In [24]:
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [25]:
print(y)

[ 5 20 14 32 22 38]


In [26]:
#create a model
model = LinearRegression()

In [27]:
#fit model
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [28]:
model = LinearRegression().fit(x, y)

In [31]:
#get results
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.715875613747954


In [32]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [33]:
print('slope:', model.coef_)

slope: [0.54]


In [36]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print('intercept:', new_model.intercept_)

intercept: [5.63333333]


In [37]:
print('slope:', new_model.coef_)

slope: [[0.54]]


In [39]:
#Predict Response
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [40]:
y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]
